name: Update README with Quote

on:
  workflow_dispatch:

jobs:
  update-quote:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # 🔥 this is the key to allow pushing changes!

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install jq -y

      - name: Get quote and update README
        run: |
          quote=$(curl -s https://zenquotes.io/api/random | jq -r '.[0].q + " — " + .[0].a')
          echo -e "\n> \"$quote\"" >> README.md

      - name: Commit & push if changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "update: add quote"
          git push
